name: Trigger auto deployment for cskt-container-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/cskt-container-app-AutoDeployTrigger-523bb3b2-7611-42aa-a507-8cf0affa8940.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CSKTCONTAINERAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CSKTCONTAINERAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CSKTCONTAINERAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: chiasekienthuc.azurecr.io
          registryUsername: ${{ secrets.CSKTCONTAINERAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CSKTCONTAINERAPP_REGISTRY_PASSWORD }}
          containerAppName: cskt-container-app
          resourceGroup: cskt
          imageToBuild: chiasekienthuc.azurecr.io/cskt-container-app:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


